language:
- python
python:
- '2.7'
before_install:
- sudo apt-get install -y curl tar
- bash travis-install-apex.sh
- eval export AWS_ACCESS_KEY_ID=\$${TRAVIS_BRANCH}_aws_access_key
- eval exportAWS_SECRET_ACCESS_KEY=\$${TRAVIS_BRANCH}_aws_secret_access_key
- eval export AWS_REGION=\$${TRAVIS_BRANCH}_aws_region
install:
- bash install-requirements.sh
- pip install coveralls
script: 
- echo "TYPE = $TRAVIS_EVENT_TYPE"
- echo "BRANCH = $TRAVIS_BRANCH"
- echo "ENV_VARS = $TRAVIS_SECURE_ENV_VARS"
- echo "AWS_REGION = $AWS_REGION"
- ls -l .
after_success:
- coveralls
deploy:
- provider: script
  skip_cleanup: true
  script: ./apex deploy 
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: ./apex deploy
  on:
    branch: master
